### ISSUE TITLE
ep1-us2  🖥️ install dependencies and libs

### ISSUE THREAD

**Issue by levinthiel** [levinthiel/KoroKoro#2]
We want to have the necessary dependencies installed and the most relevant libraries added to the project from the start.

# Tasks

- [x] commit directly to main
- [x] run `nmp i`
- [x] install these libraries:
  - [x] StyledComps
  - [x] useLocalStorage
  - [x] React icons

**Comment by StephMode** [comment]
`npm i` not necessary because `npx create next latest` already includes that

**Comment by StephMode** [comment]
In order to install the needed libraries, I had to downgrade from `react 19` to `react 18`. Lately, new Next.js projects come with `react 19` which still has pre-release status and is not supported by many libraries.
